### ISSUE TITLE
UserAgent mi yoksa API dan mi isleniyor

### ISSUE THREAD

**Issue by Ramizworking** [EmineTekcan/TwitterScrapingProject#9]
Merhabalar, 

Yaptiginiz program Twitterun API ile mi çalisiyor ?

Rate limit sorunu baya engelliyor..

Iyi gunler

**Comment by esmadl** [comment]
Merhaba,

Program Twitter API'sı ile çalışmıyor. HTML üzerinden istek gönderiyor. O yüzden program yavaş çalışıyor.
Umarım sorunuza yanıt olabilmiştir. 

İyi günler

**Comment by esmadl** [comment]
Merhaba,

Program Twitter API'sı ile çalışmıyor. HTML üzerinden istek gönderiyor. O yüzden program yavaş çalışıyor.
Umarım sorunuza yanıt olabilmiştir.

İyi günler
